name: Dump

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Clear old folders
        run: rm -Rf client && rm -Rf server        
      - name: Say version
        run: echo "Downloading ${{ env.newest_mc }}"
      - name: Setup Python
        uses: actions/setup-python@v2.2.2
      - name: Setup Java JDK
        uses: actions/setup-java@v2.0.0
        with:
          java-version: 8
          distribution: zulu
      - name: download & run decompiler
        run: |
          mkdir code
          cd code
          git clone https://github.com/hube12/DecompilerMC .
          python3 main.py --mcversion snap --side server
          ls -R
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v2.2.3
        with:
          path: .
        
