name: Dump

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: script
        run: ./.github/workflows/get_newest.sh
        shell: bash
      - name: echo
        run: echo ${{ env.newest_mc }}
